repositories {
  maven {
    url = "https://api.modrinth.com/maven"
    content {
      includeGroup "maven.modrinth"
    }
  }
}
dependencies {
  def libDir = new File(System.getProperty("user.home"), ".mcreator/lib")
  def ecaJars = fileTree(dir: libDir, include: 'eca-*-dev.jar').files
  if (!ecaJars.isEmpty()) {
    def latestEca = ecaJars.sort { it.name }.last()
    implementation files(latestEca)
  } else {
      implementation fg.deobf("maven.modrinth:epic-core-api:1.1.4-fix:dev")
  }
}


